### ISSUE TITLE
Method to collect CSI from AX86u

### ISSUE THREAD

**Issue by quantumhub** [francescamen/SHARPax#1]
Thanks for sharing the algorithm for CSI sensing processing!
I would like to collect CSI from AX86u in my indoor environment with some NLoS. Could you also share the code which is to collect CSI from AX86u?
I notice that there is a project which can collect CSI from old ac86u. But ac86u can only provide 80MHz CSI which is only half of AC86u's 160MHz bandwidth.
Very appreciate if you could help!

**Comment by francescamen** [comment]
Dear @quantumhub, 

Thank you for your interest in the code! The tool to collect the data from AX86u is AX-CSI and is available at https://ans.unibs.it/projects/ax-csi/

Best regards, 
Francesca
