### ISSUE TITLE
how to confirm the delete_idx for my own dataset

### ISSUE THREAD

**Issue by 1033020837** [francescamen/SHARPax#2]
Hi,
I want to know how to confirm the delete_idx for my own dataset? My dataset collect use ax with 250 subcarrier each ant.
![image](https://github.com/francescamen/SHARPax/assets/26853321/8353cfd1-df67-4a57-acf8-f0909691bebd)

**Comment by francescamen** [comment]
Dear @1033020837, you need to check in the IEEE 802.11ax standard the indices of the control sub-channels. This depends on the bandwidth you are using. I guess that in your case it is 20 MHz where the total number of subchannels is 256.
